@api = http://localhost:3000/api/campaigns

### Get campaigns
GET {{api}}

### Create FCDP campaign
POST {{api}}
Content-Type: application/json

{
  "type": "BRC20",
  "name": "FCDP",
  "quantity": 45316458,
  "blockStart": 845675,
  "blockEnd": 847244
}

### Create OSHI campaign
POST {{api}}
Content-Type: application/json

{
  "type": "BRC20",
  "name": "OSHI",
  "quantity": 25895119,
  "blockStart": 845675,
  "blockEnd": 847244
}

### Create CLTV campaign
POST {{api}}
Content-Type: application/json

{
  "type": "BRC20",
  "name": "CLTV",
  "quantity": 10000000,
  "blockStart": 847484,
  "blockEnd": 852524
}

### Create OSHI 2 campaign
POST {{api}}
Content-Type: application/json

{
  "type": "BRC20",
  "name": "OSHI",
  "quantity": 10000000,
  "blockStart": 846730,
  "blockEnd": 846735
}

### Create BTC campaign
POST {{api}}
Content-Type: application/json

{
  "name": "BTC",
  "quantity": 10000000,
  "blockStart": 846730,
  "blockEnd": 846735
}

### Create UNCOMMON•GOODS campaign
POST {{api}}
Content-Type: application/json

{
  "type": "Rune",
  "name": "UNCOMMON•GOODS",
  "quantity": 10000000,
  "blockStart": 846730,
  "blockEnd": 846735
}

### Get campaign
GET {{api}}/1

### Update campaign
PUT {{api}}/1
Content-Type: application/json

{
  "quantity": 1000000,
  "blockStart": 1500000,
  "blockEnd": 1502000
}

### Reset last block rewards 1
PUT {{api}}/1
Content-Type: application/json

{
  "lastBlockReward": null
}

### Reset last block rewards 1
PUT {{api}}/2
Content-Type: application/json

{
  "lastBlockReward": null
}

### Delete campaign
DELETE {{api}}/2
