@api = http://localhost:3000/api/campaigns

### Get campaigns
GET {{api}}

### Create FCDP campaign
POST {{api}}
Content-Type: application/json

{
  "name": "FCDP",
  "quantity": 1000000,
  "blockStart": 840000,
  "blockEnd": 841000,
  "lastBlockReward": 0
}

### Create OSHI campaign
POST {{api}}
Content-Type: application/json

{
  "name": "OSHI",
  "quantity": 2000000,
  "blockStart": 840000,
  "blockEnd": 841000,
  "lastBlockReward": 0
}

### Get campaign
GET {{api}}/1

### Update campaign
PUT {{api}}/1
Content-Type: application/json

{
  "quantity": 1000000,
  "blockStart": 1500000,
  "blockEnd": 1502000
}

### Reset last block rewards 1
PUT {{api}}/1
Content-Type: application/json

{
  "lastBlockReward": 0
}

### Reset last block rewards 1
PUT {{api}}/2
Content-Type: application/json

{
  "lastBlockReward": 0
}

### Delete campaign
DELETE {{api}}/3
