@api = http://localhost:3000/api/rewards

### Get rewards
GET {{api}}

### Create reward 1
POST {{api}}
Content-Type: application/json

{
  "campaignId": 1,
  "taproot": "bc1plvqwcy5chr9ja359rm4zkhyfyxacn2tj4rvjtfk40w5ctzagssnszte0m6",
  "quantity": 120
}

### Create reward 2
POST {{api}}
Content-Type: application/json

{
  "campaignId": 1,
  "taproot": "bc1pafup76rku5y3h689hpvesfgzdq28wkn6uuagepehdj9a2elzsnxqqmh9n3",
  "quantity": 1
}

### Get reward
GET {{api}}/1

### Update reward
PUT {{api}}/1
Content-Type: application/json

{
  "quantity": 50
}

### Delete reward
DELETE {{api}}/1

### Compute rewards
PUT {{api}}/compute/854373

### Compute rewards
PUT {{api}}/compute/860000
