@api = http://localhost:3000/api/stakings

### Get stakings
GET {{api}}

### Create staking 1
POST {{api}}
Content-Type: application/json

{
  "campaignId": 1,
  "address": "address1",
  "quantity": 1,
  "block": 840020
}

### Create staking 2
POST {{api}}
Content-Type: application/json

{
  "campaignId": 1,
  "address": "address2",
  "quantity": 1,
  "block": 840030
}

### Create staking 3
POST {{api}}
Content-Type: application/json

{
  "campaignId": 2,
  "address": "address1",
  "quantity": 5,
  "block": 840025
}

### Get staking
GET {{api}}/4
