@api = http://localhost:3000/api/stakings

### Get stakings
GET {{api}}

### Create staking 1
POST {{api}}
Content-Type: application/json

{
  "campaignId": 1,
  "taproot": "bc1plvqwcy5chr9ja359rm4zkhyfyxacn2tj4rvjtfk40w5ctzagssnszte0m6",
  "script": "3CXmHt6c1a7iCb6ZxZ7DvghdpSFUvVXFza",
  "txid": "269665ee8b1bf1e1f216389095e15f93d0a2c31b01208c07ae7d9f09f3c9d5df",
  "vout": 0,
  "quantity": 1
}

### Create staking 2
POST {{api}}
Content-Type: application/json

{
  "campaignId": 1,
  "taproot": "bc1pafup76rku5y3h689hpvesfgzdq28wkn6uuagepehdj9a2elzsnxqqmh9n3",
  "txid": "4474d12e7e66e4348603645f763da2aa82220eae680b193b872d719fd759f93fi0",
  "vout": 0,
  "script": "3M6XAYveXM2qbcEWz4J6PEZepN1xFgc9eM",
  "quantity": 15
}

### Create staking 3
POST {{api}}
Content-Type: application/json

{
  "campaignId": 2,
  "taproot": "bc1pafup76rku5y3h689hpvesfgzdq28wkn6uuagepehdj9a2elzsnxqqmh9n3",
  "txid": "4474d12e7e66e4348603645f763da2aa82220eae680b193b872d719fd759f93fi0",
  "vout": 0,
  "script": "3M6XAYveXM2qbcEWz4J6PEZepN1xFgc9eM",
  "quantity": 10
}

### Create staking Rune
POST {{api}}
Content-Type: application/json

{
  "campaignId": 8,
  "taproot": "bc1pafup76rku5y3h689hpvesfgzdq28wkn6uuagepehdj9a2elzsnxqqmh9n3",
  "txid": "4474d12e7e66e4348603645f763da2aa82220eae680b193b872d719fd759f93fi0",
  "vout": 0,
  "script": "3M6XAYveXM2qbcEWz4J6PEZepN1xFgc9eM",
  "quantity": 5
}

### Create staking BTC
POST {{api}}
Content-Type: application/json

{
  "campaignId": 4,
  "taproot": "bc1pafup76rku5y3h689hpvesfgzdq28wkn6uuagepehdj9a2elzsnxqqmh9n3",
  "txid": "4474d12e7e66e4348603645f763da2aa82220eae680b193b872d719fd759f93fi0",
  "vout": 0,
  "script": "3M6XAYveXM2qbcEWz4J6PEZepN1xFgc9eM",
  "quantity": 20000
}

### Update staking
POST {{api}}/4
Content-Type: application/json

{
  "block": 845020
}

### Get staking
GET {{api}}/5

### Get TVL
GET {{api}}/tvl
