@api = http://localhost:3000/api/stakings

### Get stakings
GET {{api}}

### Create staking 1
POST {{api}}
Content-Type: application/json

{
  "campaignId": 1,
  "taproot": "bc1plvqwcy5chr9ja359rm4zkhyfyxacn2tj4rvjtfk40w5ctzagssnszte0m6",
  "script": "38bmSDcEmfFS4a4gntr8D6aXe93epGw7f3",
  "quantity": 1,
  "block": 840020
}

### Create staking 2
POST {{api}}
Content-Type: application/json

{
  "campaignId": 1,
  "taproot": "bc1pafup76rku5y3h689hpvesfgzdq28wkn6uuagepehdj9a2elzsnxqqmh9n3",
  "script": "3JVfbzn43eWmXbRE8TCWoUpTWVqr79VNS4",
  "quantity": 1,
  "block": 840030
}

### Create staking 3
POST {{api}}
Content-Type: application/json

{
  "campaignId": 2,
  "taproot": "bc1plvqwcy5chr9ja359rm4zkhyfyxacn2tj4rvjtfk40w5ctzagssnszte0m6",
  "script": "38bmSDcEmfFS4a4gntr8D6aXe93epGw7f3",
  "quantity": 5,
  "block": 840025
}

### Create staking 4
POST {{api}}
Content-Type: application/json

{
  "campaignId": 1,
  "taproot": "bc1plvqwcy5chr9ja359rm4zkhyfyxacn2tj4rvjtfk40w5ctzagssnszte0m6",
  "script": "38bmSDcEmfFS4a4gntr8D6aXe93epGw7f3",
  "quantity": 1,
  "block": 840035
}

### Get staking
GET {{api}}/4
