@api = http://localhost:3000/api/user

### Get Script Address
GET {{api}}/stakingaddress
Content-Type: application/json

{
    "pubKey": "02dde3a8a673f9cba281b28077dd6928af5a4aff475af0c031df7afc5d65920b67",
    "blockheight": 847244
}

### Get Reward
GET {{api}}/reward
Content-Type: application/json

{
    "campaignId": 1,
    "taproot": "bc1plvqwcy5chr9ja359rm4zkhyfyxacn2tj4rvjtfk40w5ctzagssnszte0m6"
}
