@api = http://localhost:3000/api/user

### Get Script Address
GET {{api}}/stakingaddress
Content-Type: application/json

{
    "pubKey": "02cf541b70172a3bb2dd3cbd65728bb9655f95b6431bf9becd2c1a8d0ed33e01b8",
    "blockheight": 847244
}

### Get Reward
GET {{api}}/reward
Content-Type: application/json

{
    "campaignId": 1,
    "taproot": "bc1plvqwcy5chr9ja359rm4zkhyfyxacn2tj4rvjtfk40w5ctzagssnszte0m6"
}
